/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Task {
  createdAt?: string;
  description?: string;
  idTask?: number;
  title?: string;
  updatedAt?: string;
}
